version: '3'

volumes: 
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:
  kafka_1_log:
  kafka_2_log:
  kafka_3_log:
  zookeeper_1_data:
  zookeeper_1_log:
  zookeeper_2_data:
  zookeeper_2_log:
  zookeeper_3_data:
  zookeeper_3_log:

services:


  zookeeper_1:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper_1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_OPT: "-Dzookeeper.4lw.commands.whitelist=*"
    volumes:
      - zookeeper_1_data:/var/lib/zookeeper/data
      - zookeeper_1_log:/var/lib/zookeeper/log

  zookeeper_2:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper_2
    ports:
      - 2182:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_OPT: "-Dzookeeper.4lw.commands.whitelist=*"
    volumes:
      - zookeeper_2_data:/var/lib/zookeeper/data
      - zookeeper_2_log:/var/lib/zookeeper/log

  zookeeper_3:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper_3
    ports:
      - 2183:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_OPT: "-Dzookeeper.4lw.commands.whitelist=*"
    volumes:
      - zookeeper_3_data:/var/lib/zookeeper/data
      - zookeeper_3_log:/var/lib/zookeeper/log

  kafka_1:
    image: confluentinc/cp-kafka
    container_name: kafka_1
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: LISTEN_DOCKER_NETWORK://kafka_1:9094, LISTEN_HOST://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTEN_DOCKER_NETWORK
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTEN_DOCKER_NETWORK:PLAINTEXT,LISTEN_HOST:PLAINTEXT
    volumes:
      - kafka_1_data:/var/lib/kafka/data
      - kafka_1_log:/var/lib/kafka/log

  kafka_2:
    image: confluentinc/cp-kafka
    container_name: kafka_2
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: LISTEN_DOCKER_NETWORK://kafka_2:9095, LISTEN_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTEN_DOCKER_NETWORK
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTEN_DOCKER_NETWORK:PLAINTEXT,LISTEN_HOST:PLAINTEXT
    volumes:
      - kafka_2_data:/var/lib/kafka/data
      - kafka_2_log:/var/lib/kafka/log
  kafka_3:
    image: confluentinc/cp-kafka
    container_name: kafka_3
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: LISTEN_DOCKER_NETWORK://kafka_3:9096, LISTEN_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTEN_DOCKER_NETWORK
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTEN_DOCKER_NETWORK:PLAINTEXT,LISTEN_HOST:PLAINTEXT
    volumes:
      - kafka_3_data:/var/lib/kafka/data
      - kafka_3_log:/var/lib/kafka/log

